"""refactor_shifts_add_assignments

Revision ID: 6108da6c2f9e
Revises: 690ed089c165
Create Date: 2026-02-25 17:59:23.358328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6108da6c2f9e'
down_revision: Union[str, Sequence[str], None] = '690ed089c165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'COMPLETED', name='assignmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_shift_assignments_employee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_shift_assignments_shift_id_shifts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_assignments'))
    )
    op.add_column('shifts', sa.Column('max_employees', sa.Integer(), server_default='1', nullable=False))
    op.drop_constraint(op.f('fk_shifts_employee_id_users'), 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'employee_id')
    op.drop_column('shifts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'DECLINED', 'COMPLETED', name='shiftstatus'), autoincrement=False, nullable=False))
    op.add_column('shifts', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_shifts_employee_id_users'), 'shifts', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shifts', 'max_employees')
    op.drop_table('shift_assignments')
    # ### end Alembic commands ###
