"""add_pending_role

Revision ID: 690ed089c165
Revises: 207fa34f6afc
Create Date: 2026-02-25 13:40:49.138070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "690ed089c165"
down_revision: Union[str, Sequence[str], None] = "207fa34f6afc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'PENDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE userrole RENAME TO userrole_old;
        CREATE TYPE userrole AS ENUM ('owner', 'manager', employee');
        ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::text::userrole;
        DROP TYPE userrole_old;
    """)
    # ### end Alembic commands ###
