"""add_manager_id_to_users

Revision ID: c387bbc69b40
Revises: 6108da6c2f9e
Create Date: 2026-03-01 18:58:24.033592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c387bbc69b40'
down_revision: Union[str, Sequence[str], None] = '6108da6c2f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_id', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'manager_id')
    # ### end Alembic commands ###
