"""add_invite_codes

Revision ID: d591f3fb690e
Revises: 0e7481a6698d
Create Date: 2026-03-02 01:15:11.908982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd591f3fb690e'
down_revision: Union[str, Sequence[str], None] = '0e7481a6698d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'EMPLOYEE', 'PENDING', name='userrole'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invite_codes_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_invite_codes_manager_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], name=op.f('fk_invite_codes_used_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_invite_codes_code'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
